@startuml
'https://plantuml.com/class-diagram

abstract class oNames

oNames <|-- main
otNames <|-- main

class otNames {
filewriter;
prinf(names.size);
close();
}

abstract class main{
scan file;
Array names;
readnames();
name.sort();
closefile;
}
@enduml